version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass secret

  hbase:
    image: dajobe/hbase
    container_name: hbase
    ports:
      - "2181:2181"  # ZooKeeper
      - "16010:16010" # HBase Web UI
      - "16020:16020" # HBase RegionServer
      - "16000:16000" # HBase Master

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
