global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
  - job_name: "hbase"
    static_configs:
      - targets: ["hbase:16010"]
