server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: producer-service
          uri: http://localhost:8081
          predicates:
            - Path=/messages/**
          filters:
            - StripPrefix=1
        - id: query-service
          uri: http://localhost:8082
          predicates:
            - Path=/query/**
          filters:
            - StripPrefix=1

